language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable
  ssh_known_hosts: wetzelrice.com

cache:
  yarn: true

env:
  global:
    - JOBS=1

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --non-interactive

script:
  - yarn lint:js
  - yarn test

before_deploy:
  - openssl aes-256-cbc -K $encrypted_82e09b39369f_key -iv $encrypted_82e09b39369f_iv
    -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quite $TRAVIS_BUILD_DIR/dist deploy@wetzelrice.com:/srv/webservices/wetzelrice.com/www/wwwroot
  on:
    branch: release
